require File.expand_path(File.dirname(__FILE__) + '/../test_config.rb')
describe "Author" do
  before do
    Author.destroy_all
    @valid_author = AuthorHelper.author.attributes
    @mononym_author = AuthorHelper.mononym.attributes
  end

  it "should create an instance of a valid author" do
    author = Author.new(@valid_author)
    author.valid?.must_equal true
  end
  
  it "should have an autogenerated ID" do
    author = Author.create(@valid_author)
    author.id.wont_be_nil
  end

  describe "name" do
    it "should have at least one name" do
      @valid_author[:first_name] = ""
      @valid_author[:last_name] = ""
      @valid_author[:middle_name] = ""
      author = Author.new(@valid_author)
      author.valid?.wont_equal true
      author.errors.messages[:first_name].must_include "Author must have at least one name"
      author.errors.messages[:middle_name].must_include "Author must have at least one name"
      author.errors.messages[:last_name].must_include "Author must have at least one name"
    end

    it "should generate the correct full_name" do
      author = Author.new(@valid_author)
      middle_name_author = Author.create(AuthorHelper.middle_name.attributes)
      author.full_name.must_equal "Albert Einstein"
      mononym_author = Author.create(@mononym_author)
      mononym_author.full_name.must_equal "Plato"
      middle_name_author.full_name.must_equal "George R. R. Martin"
    end
    
    it "should generate a first_name_last_name if these are present" do
      author = Author.new(@valid_author)
      author.first_name_last_name.must_equal "Albert Einstein"
    end

    it "should not have a title that exceeds 10 characters" do
      @valid_author[:title] = "t"*11
      author = Author.new(@valid_author)
      author.valid?.wont_equal true
    end
  end
  
  describe "biography" do
    it "should exist" do
      @valid_author[:biography] = ""
      author = Author.new(@valid_author)
      author.valid?.wont_equal true
    end

    it "must be at least 10 characters long" do
      @valid_author[:biography] = "b"*9
      author = Author.new(@valid_author)
      author.valid?.wont_equal true
    end

    it "should be unique" do
      Author.create(@valid_author)
      @mononym_author[:biography] = @valid_author[:biography]
      author = Author.new(@mononym_author)
      author.valid?.wont_equal true
    end
  end

end
